CONTAINER ExportToUnityNoFBX
{
	NAME ExportToUnityNoFBX;
    INCLUDE Tbase;

    GROUP ID_TAGPROPERTIES
	{
		FILENAME EXPORTTOUNITY_PATH { DIRECTORY; ANIM OFF; }
		
		SEPARATOR { LINE; }
		
		STRING EXPORTTOUNITY_FILENAME_OVERRIDE { ANIM OFF; }
		LONG EXPORTTOUNITY_FILEFORMAT { CYCLE { EXPORTTOUNITY_FILEFORMAT_FBX; EXPORTTOUNITY_FILEFORMAT_C4D; } ANIM OFF; }
		
		SEPARATOR EXPORTTOUNITY_GRP_COMMAND_OPTIONS {}
		
		BOOL EXPORTTOUNITY_DO_CURRENT_STATE_TO_OBJECT { ANIM OFF; }
		BOOL EXPORTTOUNITY_DO_CONNECT_AND_DELETE { ANIM OFF; }
	}
}
