#ifndef _ExportToUnityNoFBX_H_
#define _ExportToUnityNoFBX_H_

enum
{
	EXPORTTOUNITY_PATH = 1001,
	
	EXPORTTOUNITY_FILENAME_OVERRIDE = 1004,
	
	EXPORTTOUNITY_FILEFORMAT = 1002,
	
	EXPORTTOUNITY_FILEFORMAT_FBX = 10001,
	EXPORTTOUNITY_FILEFORMAT_C4D = 10002,
	
	EXPORTTOUNITY_GRP_COMMAND_OPTIONS = 2001,
	
	EXPORTTOUNITY_DO_CURRENT_STATE_TO_OBJECT = 1005,
	EXPORTTOUNITY_DO_CONNECT_AND_DELETE = 1006,
	
	EXPORTTOUNITY_GRP_FBX_OPTIONS = 2000,
	
	EXPORTTOUNITY_OVERRIDE_FBX_PREFS = 1007,
	EXPORTTOUNITY_COPY_FBX_PREFS_BUTTON = 1008,
	
	EXPORTTOUNITY_FBXEXPORT_ASCII_OVERRIDE = 1009,
	EXPORTTOUNITY_FBXEXPORT_LIGHTS_OVERRIDE = 1010,
	EXPORTTOUNITY_FBXEXPORT_CAMERAS_OVERRIDE = 1011,
	EXPORTTOUNITY_FBXEXPORT_SPLINES_OVERRIDE = 1012,
	EXPORTTOUNITY_FBXEXPORT_SDS_OVERRIDE = 1013,
	EXPORTTOUNITY_FBXEXPORT_TRACKS_OVERRIDE = 1014,
	EXPORTTOUNITY_FBXEXPORT_BAKE_ALL_FRAMES_OVERRIDE = 1015,
	EXPORTTOUNITY_FBXEXPORT_PLA_TO_VERTEXCACHE_OVERRIDE = 1016,
	EXPORTTOUNITY_FBXEXPORT_SAVE_NORMALS_OVERRIDE = 1017,
	EXPORTTOUNITY_FBXEXPORT_SAVE_VERTEX_MAPS_AS_COLORS_OVERRIDE = 1018,
	EXPORTTOUNITY_FBXEXPORT_SAVE_VERTEX_COLORS_OVERRIDE = 1019,
	EXPORTTOUNITY_FBXEXPORT_TRIANGULATE_OVERRIDE = 1020,
	EXPORTTOUNITY_FBXEXPORT_SDS_SUBDIVISION_OVERRIDE = 1021,
	EXPORTTOUNITY_FBXEXPORT_TEXTURES_OVERRIDE = 1022,
	EXPORTTOUNITY_FBXEXPORT_EMBED_TEXTURES_OVERRIDE = 1023,
	EXPORTTOUNITY_FBXEXPORT_SUBSTANCES_OVERRIDE = 1024,

	EXPORTTOUNITY_ERRORS = 1050,
	EXPORTTOUNITY_WARNINGS = 1051,
	EXPORTTOUNITY_FINAL_PATH = 1052,
	
	EXPORTTOUNITY_FBXEXPORT_TEXT_LABEL = 1025,
};

#endif
