CONTAINER ExportToUnity
{
	NAME ExportToUnity;
    INCLUDE Tbase;

    GROUP ID_TAGPROPERTIES
	{
		FILENAME EXPORTTOUNITY_PATH { DIRECTORY; ANIM OFF; }
		
		SEPARATOR { LINE; }
		
		STRING EXPORTTOUNITY_FILENAME_OVERRIDE { ANIM OFF; }
		LONG EXPORTTOUNITY_FILEFORMAT { CYCLE { EXPORTTOUNITY_FILEFORMAT_FBX; EXPORTTOUNITY_FILEFORMAT_C4D; } ANIM OFF; }
		
		SEPARATOR EXPORTTOUNITY_GRP_COMMAND_OPTIONS {}
		
		BOOL EXPORTTOUNITY_DO_CURRENT_STATE_TO_OBJECT { ANIM OFF; }
		BOOL EXPORTTOUNITY_DO_CONNECT_AND_DELETE { ANIM OFF; }
	
		SEPARATOR EXPORTTOUNITY_GRP_FBX_OPTIONS {}
		
		BOOL EXPORTTOUNITY_OVERRIDE_FBX_PREFS { PARENTCOLLAPSE; ANIM OFF; }
	
		SEPARATOR { LINE; PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; }
	
		BOOL EXPORTTOUNITY_FBXEXPORT_ASCII_OVERRIDE { PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; ANIM OFF; }
	
		SEPARATOR { LINE; PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; }
	
		BOOL EXPORTTOUNITY_FBXEXPORT_LIGHTS_OVERRIDE { PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; ANIM OFF; }
		BOOL EXPORTTOUNITY_FBXEXPORT_CAMERAS_OVERRIDE { PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; ANIM OFF; }
		BOOL EXPORTTOUNITY_FBXEXPORT_SPLINES_OVERRIDE { PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; ANIM OFF; }
		BOOL EXPORTTOUNITY_FBXEXPORT_SDS_OVERRIDE { PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; ANIM OFF; }

		SEPARATOR { LINE; PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; }
	
		BOOL EXPORTTOUNITY_FBXEXPORT_TRACKS_OVERRIDE { PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; ANIM OFF; }
		BOOL EXPORTTOUNITY_FBXEXPORT_BAKE_ALL_FRAMES_OVERRIDE { PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; ANIM OFF; }
		BOOL EXPORTTOUNITY_FBXEXPORT_PLA_TO_VERTEXCACHE_OVERRIDE { PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; ANIM OFF; }
	
		SEPARATOR { LINE; PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; }
	
		BOOL EXPORTTOUNITY_FBXEXPORT_SAVE_NORMALS_OVERRIDE { PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; ANIM OFF; }
		BOOL EXPORTTOUNITY_FBXEXPORT_SAVE_VERTEX_MAPS_AS_COLORS_OVERRIDE { PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; ANIM OFF; }
		BOOL EXPORTTOUNITY_FBXEXPORT_SAVE_VERTEX_COLORS_OVERRIDE { PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; ANIM OFF; }
		BOOL EXPORTTOUNITY_FBXEXPORT_TRIANGULATE_OVERRIDE { PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; ANIM OFF; }
		BOOL EXPORTTOUNITY_FBXEXPORT_SDS_SUBDIVISION_OVERRIDE { PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; ANIM OFF; }
	
		SEPARATOR { LINE; PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; }
	
		BOOL EXPORTTOUNITY_FBXEXPORT_TEXTURES_OVERRIDE { PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; ANIM OFF; }
		BOOL EXPORTTOUNITY_FBXEXPORT_EMBED_TEXTURES_OVERRIDE { PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; ANIM OFF; }
		BOOL EXPORTTOUNITY_FBXEXPORT_SUBSTANCES_OVERRIDE { PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; ANIM OFF; }
	
		SEPARATOR { LINE; PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; }
	
		BUTTON EXPORTTOUNITY_COPY_FBX_PREFS_BUTTON { PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; ANIM OFF; }
		
		SEPARATOR { LINE; PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; }
		
		STATICTEXT EXPORTTOUNITY_FBXEXPORT_TEXT_LABEL { PARENTCOLLAPSE EXPORTTOUNITY_OVERRIDE_FBX_PREFS; ANIM OFF; }
	}
}
