# -*- coding: utf8 -*-

import c4d

# constants

MAIN_COMMAND_PLUGIN_ID = 1034321
MAIN_COMMAND_NAME = "Do the export to Unity"
MAIN_COMMAND_HELP = "A plug in that helps with getting stuff out of Cinema 4D and into Unity"

MAIN_MENU_TITLE = "Unity"
MAIN_PLUGIN_COMMAND = "PLUGIN_CMD_" + str( MAIN_COMMAND_PLUGIN_ID )

MAIN_TAG_PLUGIN_ID = 1034322
MAIN_TAG_TAGNAME = "Export to Unity"
MAIN_TAG_DESCRIPTION = "ExportToUnity"
MAIN_TAG_DESCRIPTION_NO_FBX = "ExportToUnityNoFBX"

STOP_TAG_PLUGIN_ID = 1039243
STOP_TAG_TAGNAME = "Exclude object and children"
STOP_TAG_DESCRIPTION = "StopTag"

TOGGLE_CLEAR_CONSOLE_COMMAND_PLUGIN_ID = 1039238
TOGGLE_CLEAR_CONSOLE_COMMAND = "PLUGIN_CMD_" + str( TOGGLE_CLEAR_CONSOLE_COMMAND_PLUGIN_ID )
TOGGLE_CLEAR_CONSOLE_COMMAND_NAME = "Clear console each time"
TOGGLE_CLEAR_CONSOLE_COMMAND_HELP = "Clears console before starting Unity export"

TOGGLE_DO_SAVE_COMMAND_PLUGIN_ID = 1039239
TOGGLE_DO_SAVE_COMMAND = "PLUGIN_CMD_" + str( TOGGLE_DO_SAVE_COMMAND_PLUGIN_ID )
TOGGLE_DO_SAVE_COMMAND_NAME = "Do Cinema 4D “Save” command"
TOGGLE_DO_SAVE_COMMAND_HELP = "Does a standard Cinema 4D save command before doing the Unity export"

# various options/flags used with c4d.documents.SaveDocument in "Export" method

SAVE_DOCUMENT_FLAGS = c4d.SAVEDOCUMENTFLAGS_DONTADDTORECENTLIST

C4D_OPTION_SAVE_AS_C4D = c4d.FORMAT_C4DEXPORT
C4D_OPTION_SAVE_AS_FBX = 1026370

FBX_EXPORTER_ID = 1026370

# command codes ( for use with c4d.CallCommand )

COMMAND_CURRENT_STATE_TO_OBJECT = 12233
COMMAND_SELECT_CHILDREN = 16388
COMMAND_CONNECT_AND_DELETE = 16768
COMMAND_DELETE = 12109
COMMAND_CLEAR_CONSOLE = 13957
COMMAND_SAVE = 12098
COMMAND_SHOW_CONSOLE = 12305

# preferences ( c4d.plugins.GetWorldPluginData etc )

PREF_DO_C4D_SAVE_COMMAND = 1
PREF_DO_CLEAR_CONSOLE = 2
PREF_LAST_PATH = 3

# file type extensions

FILEEXTENSION_FBX = "fbx"
FILEEXTENSION_C4D = "c4d"

# defaults (for new tags applied to objects for the first time)

TAG_DEFAULT_FILEFORMAT = 10001   #c4d.EXPORTTOUNITY_FILEFORMAT_FBX
#TAG_DEFAULT_FILEFORMAT = c4d.EXPORTTOUNITY_FILEFORMAT_FBX

# miscellaneous

NEWLINE = "\n"
PRINTED_NEWLINE = " " + NEWLINE

MINIMUM_C4D_VERSION_REQUIRED_FOR_FBX_OVERRIDE = 16000
NAME_OF_EDITOR_MENUS = "M_EDITOR"